### ISSUE TITLE
Error: Unable to load recipe.

### ISSUE THREAD

**Issue by skoobasteeve** [VincentMeilinger/Nextcloud-Cookbook-iOS#24]
First of all, I LOVE this app. Looks so clean on iOS.

I had this error on a specific recipe when I was trying it out today: "Error: Unable to load recipe". This recipe is viewable on the web app as well as the other Nextcloud Cookbook iOS app. See attached screenshot and JSON.

[recipe.json](https://github.com/VincentMeilinger/Nextcloud-Cookbook-iOS/files/15211036/recipe.json)

![IMG_0378_small](https://github.com/VincentMeilinger/Nextcloud-Cookbook-iOS/assets/36998292/b13f382e-c5ee-4c30-af82-04f8bae1320d)

Thank you again for your work! Hope you keep at it.

**Comment by VincentMeilinger** [comment]
Hey @skoobasteeve, 

Thank you for your kind words, I'm glad you like the app :)
I'll look into this and come back to you if I find the issue.

**Comment by VincentMeilinger** [comment]
Hey @skoobasteeve,
since you provided the recipe json, finding the issue was easy. The nutrition section contains an integer value for calories, but the app expects a string. Since the schema.org recipe standard is really flexible, it's difficult to parse every format that exists. My recipe structure is quite rigid at the moment, but I'm already looking for better solutions. 

```json
"nutrition": {
    "@context": "http:\/\/schema.org",
    "@type": "NutritionInformation",
    "calories": 205,  // This is a numeric value, but the app expects a string.
    "unsaturatedFatContent": "3 grams",
    "carbohydrateContent": "31 grams",
    "fatContent": "8 grams",
    "fiberContent": "1 gram",
    "proteinContent": "2 grams",
    "saturatedFatContent": "5 grams",
    "sodiumContent": "111 milligrams",
    "sugarContent": "17 grams",
    "transFatContent": "0 grams"
  },
```

For now, you could change the integer to a string, or wait until the next update :)

**Comment by skoobasteeve** [comment]
@VincentMeilinger Thank you for the fast response and fix!

**Comment by VincentMeilinger** [comment]
@skoobasteeve glad i could help :)
